url: "https://www.tiny.cloud"
permalink: pretty
origin: "https://www.tiny.cloud"
baseurl: ""
shared_baseurl: ""
syntax_highlight_theme: "tomorrow-night"
cdnurl: "https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
tinymce_codepen_url: "https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/5/tinymce.min.js"
tinydrive_codepen_url: "https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinydrive/stable/tinydrive.min.js"
default_meta_keywords: tinymce, documentation, docs, plugins, customizable skins, configuration, examples, html, php, java, javascript, image editor, inline editor, distraction-free editor, classic editor
# product variables
productname: TinyMCE
productversion: 5
releaseversion: 5.0
companyname: Tiny Technologies, Inc.
cloudname: Tiny Cloud
accountsignup: https://www.tiny.cloud/auth/signup
# HMTL entities
tick: '&#10004;'
cross: '&#10006;'
nbsp: '&#160;'
tab: '&#160;&#160;'
newline: '<br>'

thirdPartyInteg: "> **Important**: This Integration is maintained by a third-party developer. Tiny Technologies, Inc. bears no responsibility for this integration, which is not covered by the Tiny Self-Hosted Software License Agreement. For issues related to the integration, contact the third-party project directly."

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - wercker.yml
  - node_modules
  - .idea
  - .git

# redcarpet was messing up some of the codepens
markdown: kramdown

kramdown:
  syntax-highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'prettyprint'

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-sitemap

